# Tells hubake what version of the tools we expect.

[system]
source = "git"
repo = "https://github.com/Karthik-d-k/exhubris-riscv-hazard3"
rev = "09d31a77f47521177cfb3309a6cc71e978779ff8"               # branch: rp235x-cortex-m33
