# Tells hubake what version of the tools we expect.

[system]
source = "git"
repo = "https://github.com/Karthik-d-k/exhubris-riscv-hazard3"
rev = "263e1686d9f84e27454298cf6e4627b847d863df"               # branch:  no-pmp-rp235x-hazard3  

